# Generated by Django 3.0.5 on 2020-11-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='media/image/actors/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Ganre',
                'verbose_name_plural': 'Ganres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('poster', models.ImageField(height_field=632, upload_to='', verbose_name='Poster', width_field=432)),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Date')),
                ('description_view', models.TextField(blank=True, verbose_name='Short description')),
                ('description_detail', models.TextField(blank=True, verbose_name='Detailed description')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('completed', models.BooleanField(default=False, verbose_name='Сompleted')),
                ('actors', models.ManyToManyField(blank=True, related_name='movie_actor', to='movies.Actor', verbose_name='Actor')),
                ('genres', models.ManyToManyField(blank=True, to='movies.Genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='media/image/actors/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(default=1, verbose_name='Season')),
                ('episodes', models.PositiveSmallIntegerField(default=1, verbose_name='Episodes')),
                ('language', models.CharField(max_length=20, verbose_name='Language')),
                ('voice_acting', models.CharField(max_length=50, verbose_name='Voice acting')),
                ('quality', models.PositiveSmallIntegerField(default=360, verbose_name='Quality')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Frame',
                'verbose_name_plural': 'Frames',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='movie_producer', to='movies.Producer', verbose_name='Producer'),
        ),
    ]
