# Generated by Django 3.0.5 on 2020-11-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Shot', 'verbose_name_plural': 'Shots'},
        ),
    ]
