# Generated by Django 3.0.5 on 2020-11-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201112_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.AlterField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='movie_producer', to='movies.Actor', verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='season',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movie', verbose_name='Movie'),
        ),
    ]
