# Generated by Django 3.0.5 on 2020-11-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201112_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='', verbose_name='Poster'),
        ),
    ]
