# Generated by Django 3.0.5 on 2020-11-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201112_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Movie'),
        ),
    ]
