# Generated by Django 3.0.5 on 2020-11-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_film_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description_view',
            new_name='description_short',
        ),
    ]
