# Generated by Django 3.0.5 on 2020-11-12 23:35

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20201113_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='video',
            field=models.FileField(null=True, upload_to=movies.models.get_trailer_path),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='media/actors/', verbose_name='Image'),
        ),
    ]
