# Generated by Django 3.0.5 on 2020-11-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
