# Generated by Django 3.0.5 on 2020-11-14 04:58

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_season_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to=movies.models.get_poster_path, verbose_name='Poster'),
        ),
    ]
