# Generated by Django 3.1.3 on 2020-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20201118_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, to='movies.Country', verbose_name='Country'),
        ),
    ]
