# Generated by Django 3.1.3 on 2020-11-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20201121_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countres'},
        ),
    ]
